# Form implementation generated from reading ui file 'c:\Users\kahra\OneDrive\Masaüstü\PROGRAM\PYTHON\PROJECT\PYQT6_PROJECTS\TAMAMLANANLAR\PROJE\VIT_Project\Application3.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1044, 812)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(1228, 805))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setStyleSheet("QWidget {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 rgba(173, 216, 230, 255), \n"
"        stop:1 rgba(255, 255, 255, 255));\n"
"};\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 95))
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: #005f73;\n"
"}border-radius: 10px;\n"
"background-color: #008CBA;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.W_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.W_widget.setEnabled(True)
        self.W_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.W_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.W_widget.setFont(font)
        self.W_widget.setAcceptDrops(False)
        self.W_widget.setStyleSheet("border: 2px solid #ccc;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"QWidget {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 rgba(173, 216, 230, 255), \n"
"        stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.W_widget.setObjectName("W_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.W_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.PB_duplicate_record_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_duplicate_record_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_duplicate_record_button.setFont(font)
        self.PB_duplicate_record_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.PB_duplicate_record_button.setObjectName("PB_duplicate_record_button")
        self.gridLayout.addWidget(self.PB_duplicate_record_button, 3, 0, 1, 1)
        self.PB_all_applications_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_all_applications_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_all_applications_button.setFont(font)
        self.PB_all_applications_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.PB_all_applications_button.setObjectName("PB_all_applications_button")
        self.gridLayout.addWidget(self.PB_all_applications_button, 2, 0, 1, 1)
        self.LE_search_input = QtWidgets.QLineEdit(parent=self.W_widget)
        self.LE_search_input.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LE_search_input.setFont(font)
        self.LE_search_input.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.LE_search_input.setObjectName("LE_search_input")
        self.gridLayout.addWidget(self.LE_search_input, 1, 2, 1, 1)
        self.PB_search_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_search_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_search_button.setFont(font)
        self.PB_search_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.PB_search_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.PB_search_button.setObjectName("PB_search_button")
        self.gridLayout.addWidget(self.PB_search_button, 1, 0, 1, 1)
        self.PB_mentor_meeting_defined_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_mentor_meeting_defined_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_mentor_meeting_defined_button.setFont(font)
        self.PB_mentor_meeting_defined_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.PB_mentor_meeting_defined_button.setObjectName("PB_mentor_meeting_defined_button")
        self.gridLayout.addWidget(self.PB_mentor_meeting_defined_button, 4, 0, 1, 1)
        self.CB_combo_box = QtWidgets.QComboBox(parent=self.W_widget)
        self.CB_combo_box.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CB_combo_box.setFont(font)
        self.CB_combo_box.setStyleSheet("QComboBox {\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #ccc;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"")
        self.CB_combo_box.setMaxVisibleItems(11)
        self.CB_combo_box.setObjectName("CB_combo_box")
        self.CB_combo_box.addItem("")
        self.CB_combo_box.addItem("")
        self.CB_combo_box.addItem("")
        self.CB_combo_box.addItem("")
        self.gridLayout.addWidget(self.CB_combo_box, 2, 2, 1, 1)
        self.PB_mentor_interview_undefined_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_mentor_interview_undefined_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_mentor_interview_undefined_button.setFont(font)
        self.PB_mentor_interview_undefined_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.PB_mentor_interview_undefined_button.setObjectName("PB_mentor_interview_undefined_button")
        self.gridLayout.addWidget(self.PB_mentor_interview_undefined_button, 4, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(2, 2)
        self.verticalLayout_2.addWidget(self.W_widget)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setSizeIncrement(QtCore.QSize(1228, 805))
        self.tableWidget.setBaseSize(QtCore.QSize(1228, 805))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    \n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #f9f9f9;\n"
"    alternate-background-color: #e0e0e0;\n"
"    gridline-color: #ccc;\n"
"    border-radius: 10px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(255)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_return_to_preferences_screen_button = QtWidgets.QPushButton(parent=self.frame)
        self.PB_return_to_preferences_screen_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PB_return_to_preferences_screen_button.setFont(font)
        self.PB_return_to_preferences_screen_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.PB_return_to_preferences_screen_button.setObjectName("PB_return_to_preferences_screen_button")
        self.horizontalLayout.addWidget(self.PB_return_to_preferences_screen_button)
        self.PB_EXIT = QtWidgets.QPushButton(parent=self.frame)
        self.PB_EXIT.setMinimumSize(QtCore.QSize(0, 60))
        self.PB_EXIT.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}")
        self.PB_EXIT.setObjectName("PB_EXIT")
        self.horizontalLayout.addWidget(self.PB_EXIT)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APPLICATIONS"))
        self.label.setText(_translate("MainWindow", "APPLICATIONS"))
        self.PB_duplicate_record_button.setText(_translate("MainWindow", "Duplicate Record"))
        self.PB_all_applications_button.setText(_translate("MainWindow", "All Applications"))
        self.LE_search_input.setPlaceholderText(_translate("MainWindow", " Write a name or surname..."))
        self.PB_search_button.setText(_translate("MainWindow", "Search"))
        self.PB_mentor_meeting_defined_button.setText(_translate("MainWindow", "Mentor Interview Defined"))
        self.CB_combo_box.setCurrentText(_translate("MainWindow", "   Please make a choice..."))
        self.CB_combo_box.setItemText(0, _translate("MainWindow", "   Please make a choice..."))
        self.CB_combo_box.setItemText(1, _translate("MainWindow", "    Previous VIT Control"))
        self.CB_combo_box.setItemText(2, _translate("MainWindow", "      Different Records"))
        self.CB_combo_box.setItemText(3, _translate("MainWindow", "        Applying Filter"))
        self.PB_mentor_interview_undefined_button.setText(_translate("MainWindow", "Mentor Interview Undefined"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name Surname"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mentor Situation"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "VIT"))
        self.PB_return_to_preferences_screen_button.setText(_translate("MainWindow", "Return to Preferences Screen"))
        self.PB_EXIT.setText(_translate("MainWindow", "EXIT"))
