# Form implementation generated from reading ui file 'Application.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApplicationWindow(object):
    def setupUi(self, ApplicationWindow):
        ApplicationWindow.setObjectName("ApplicationWindow")
        ApplicationWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        ApplicationWindow.setEnabled(True)
        ApplicationWindow.resize(1098, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ApplicationWindow.sizePolicy().hasHeightForWidth())
        ApplicationWindow.setSizePolicy(sizePolicy)
        ApplicationWindow.setMinimumSize(QtCore.QSize(0, 0))
        ApplicationWindow.setSizeIncrement(QtCore.QSize(0, 0))
        ApplicationWindow.setBaseSize(QtCore.QSize(1228, 805))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        ApplicationWindow.setFont(font)
        ApplicationWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        ApplicationWindow.setStyleSheet("QWidget {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 rgba(173, 216, 230, 255), \n"
"        stop:1 rgba(255, 255, 255, 255));\n"
"};\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=ApplicationWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 95))
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: #005f73;\n"
"}border-radius: 10px;\n"
"background-color: #008CBA;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.W_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.W_widget.setEnabled(True)
        self.W_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.W_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.W_widget.setFont(font)
        self.W_widget.setAcceptDrops(False)
        self.W_widget.setStyleSheet("border: 2px solid #ccc;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"QWidget {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 rgba(173, 216, 230, 255), \n"
"        stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.W_widget.setObjectName("W_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.W_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.PB_mentor_meeting_defined_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_mentor_meeting_defined_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.PB_mentor_meeting_defined_button.setFont(font)
        self.PB_mentor_meeting_defined_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_mentor_meeting_defined_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/members.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_mentor_meeting_defined_button.setIcon(icon)
        self.PB_mentor_meeting_defined_button.setIconSize(QtCore.QSize(50, 50))
        self.PB_mentor_meeting_defined_button.setObjectName("PB_mentor_meeting_defined_button")
        self.gridLayout.addWidget(self.PB_mentor_meeting_defined_button, 2, 3, 1, 1)
        self.PB_return_to_preferences_screen_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_return_to_preferences_screen_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.PB_return_to_preferences_screen_button.setFont(font)
        self.PB_return_to_preferences_screen_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_return_to_preferences_screen_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/news.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_return_to_preferences_screen_button.setIcon(icon1)
        self.PB_return_to_preferences_screen_button.setIconSize(QtCore.QSize(50, 50))
        self.PB_return_to_preferences_screen_button.setObjectName("PB_return_to_preferences_screen_button")
        self.gridLayout.addWidget(self.PB_return_to_preferences_screen_button, 4, 0, 1, 1)
        self.PB_mentor_interview_undefined_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_mentor_interview_undefined_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.PB_mentor_interview_undefined_button.setFont(font)
        self.PB_mentor_interview_undefined_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_mentor_interview_undefined_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/users.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_mentor_interview_undefined_button.setIcon(icon2)
        self.PB_mentor_interview_undefined_button.setIconSize(QtCore.QSize(50, 50))
        self.PB_mentor_interview_undefined_button.setObjectName("PB_mentor_interview_undefined_button")
        self.gridLayout.addWidget(self.PB_mentor_interview_undefined_button, 2, 2, 1, 1)
        self.LE_search_input = QtWidgets.QLineEdit(parent=self.W_widget)
        self.LE_search_input.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.LE_search_input.setFont(font)
        self.LE_search_input.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.LE_search_input.setObjectName("LE_search_input")
        self.gridLayout.addWidget(self.LE_search_input, 1, 2, 1, 2)
        self.PB_search_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_search_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.PB_search_button.setFont(font)
        self.PB_search_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_search_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.PB_search_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/search-user.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_search_button.setIcon(icon3)
        self.PB_search_button.setIconSize(QtCore.QSize(50, 50))
        self.PB_search_button.setObjectName("PB_search_button")
        self.gridLayout.addWidget(self.PB_search_button, 1, 1, 1, 1)
        self.PB_all_applications_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_all_applications_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.PB_all_applications_button.setFont(font)
        self.PB_all_applications_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_all_applications_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/user-groups.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_all_applications_button.setIcon(icon4)
        self.PB_all_applications_button.setIconSize(QtCore.QSize(50, 50))
        self.PB_all_applications_button.setObjectName("PB_all_applications_button")
        self.gridLayout.addWidget(self.PB_all_applications_button, 1, 0, 1, 1)
        self.PB_duplicate_record_button = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_duplicate_record_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.PB_duplicate_record_button.setFont(font)
        self.PB_duplicate_record_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_duplicate_record_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/orders.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_duplicate_record_button.setIcon(icon5)
        self.PB_duplicate_record_button.setIconSize(QtCore.QSize(50, 50))
        self.PB_duplicate_record_button.setObjectName("PB_duplicate_record_button")
        self.gridLayout.addWidget(self.PB_duplicate_record_button, 2, 0, 1, 1)
        self.CB_combo_box = QtWidgets.QComboBox(parent=self.W_widget)
        self.CB_combo_box.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.CB_combo_box.setFont(font)
        self.CB_combo_box.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.CB_combo_box.setMouseTracking(False)
        self.CB_combo_box.setStyleSheet("QComboBox {\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #ccc;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"")
        self.CB_combo_box.setMaxVisibleItems(11)
        self.CB_combo_box.setObjectName("CB_combo_box")
        self.CB_combo_box.addItem("")
        self.CB_combo_box.addItem("")
        self.CB_combo_box.addItem("")
        self.CB_combo_box.addItem("")
        self.gridLayout.addWidget(self.CB_combo_box, 4, 2, 1, 2)
        self.PB_exit = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_exit.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.PB_exit.setFont(font)
        self.PB_exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_exit.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/power.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_exit.setIcon(icon6)
        self.PB_exit.setIconSize(QtCore.QSize(50, 50))
        self.PB_exit.setObjectName("PB_exit")
        self.gridLayout.addWidget(self.PB_exit, 4, 1, 1, 1)
        self.PB_duplicate_record_button_2 = QtWidgets.QPushButton(parent=self.W_widget)
        self.PB_duplicate_record_button_2.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.PB_duplicate_record_button_2.setFont(font)
        self.PB_duplicate_record_button_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_duplicate_record_button_2.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/checklist.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_duplicate_record_button_2.setIcon(icon7)
        self.PB_duplicate_record_button_2.setIconSize(QtCore.QSize(50, 50))
        self.PB_duplicate_record_button_2.setObjectName("PB_duplicate_record_button_2")
        self.gridLayout.addWidget(self.PB_duplicate_record_button_2, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 2)
        self.verticalLayout_2.addWidget(self.W_widget)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setSizeIncrement(QtCore.QSize(1228, 805))
        self.tableWidget.setBaseSize(QtCore.QSize(1228, 805))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    \n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #f9f9f9;\n"
"    alternate-background-color: #e0e0e0;\n"
"    gridline-color: #ccc;\n"
"    border-radius: 10px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(204)
        self.verticalLayout_2.addWidget(self.tableWidget)
        ApplicationWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ApplicationWindow)
        self.statusbar.setObjectName("statusbar")
        ApplicationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ApplicationWindow)
        QtCore.QMetaObject.connectSlotsByName(ApplicationWindow)

    def retranslateUi(self, ApplicationWindow):
        _translate = QtCore.QCoreApplication.translate
        ApplicationWindow.setWindowTitle(_translate("ApplicationWindow", "APPLICATIONS"))
        self.label.setText(_translate("ApplicationWindow", "APPLICATIONS"))
        self.PB_mentor_meeting_defined_button.setText(_translate("ApplicationWindow", "Mentor Interview Defined"))
        self.PB_return_to_preferences_screen_button.setText(_translate("ApplicationWindow", "Main Menu      "))
        self.PB_mentor_interview_undefined_button.setText(_translate("ApplicationWindow", "Mentor Interview Undefined"))
        self.LE_search_input.setPlaceholderText(_translate("ApplicationWindow", "     Write a name or surname..."))
        self.PB_search_button.setText(_translate("ApplicationWindow", "Search             "))
        self.PB_all_applications_button.setText(_translate("ApplicationWindow", "All Applications  "))
        self.PB_duplicate_record_button.setText(_translate("ApplicationWindow", "Duplicate Record"))
        self.CB_combo_box.setCurrentText(_translate("ApplicationWindow", "   Please make a choice..."))
        self.CB_combo_box.setItemText(0, _translate("ApplicationWindow", "   Please make a choice..."))
        self.CB_combo_box.setItemText(1, _translate("ApplicationWindow", "    Previous VIT Control"))
        self.CB_combo_box.setItemText(2, _translate("ApplicationWindow", "      Different Records"))
        self.CB_combo_box.setItemText(3, _translate("ApplicationWindow", "        Applying Filter"))
        self.PB_exit.setText(_translate("ApplicationWindow", "  Exit               "))
        self.PB_duplicate_record_button_2.setText(_translate("ApplicationWindow", "Differend Record"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ApplicationWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ApplicationWindow", "Surname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ApplicationWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ApplicationWindow", "Mentor Situation"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ApplicationWindow", "VIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicationWindow = QtWidgets.QMainWindow()
    ui = Ui_ApplicationWindow()
    ui.setupUi(ApplicationWindow)
    ApplicationWindow.show()
    sys.exit(app.exec())
