# Form implementation generated from reading ui file 'c:\Users\kahra\OneDrive\Masaüstü\PROGRAM\PYTHON\PROJECT\PYQT6_PROJECTS\TAMAMLANANLAR\PROJE\VIT_Project\interviews.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_interviews(object):
    def setupUi(self, interviews):
        interviews.setObjectName("interviews")
        interviews.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        interviews.setEnabled(True)
        interviews.resize(734, 548)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(interviews.sizePolicy().hasHeightForWidth())
        interviews.setSizePolicy(sizePolicy)
        interviews.setMinimumSize(QtCore.QSize(0, 0))
        interviews.setSizeIncrement(QtCore.QSize(0, 0))
        interviews.setBaseSize(QtCore.QSize(1228, 805))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        interviews.setFont(font)
        interviews.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        interviews.setStyleSheet("QWidget {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 rgba(173, 216, 230, 255), \n"
"        stop:1 rgba(255, 255, 255, 255));\n"
"};\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=interviews)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 95))
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: #005f73;\n"
"}border-radius: 10px;\n"
"background-color: #008CBA;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame_mentor_preference = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_mentor_preference.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.frame_mentor_preference.setFont(font)
        self.frame_mentor_preference.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_mentor_preference.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_mentor_preference.setObjectName("frame_mentor_preference")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_mentor_preference)
        self.gridLayout.setObjectName("gridLayout")
        self.PB_interrview_exit = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_interrview_exit.sizePolicy().hasHeightForWidth())
        self.PB_interrview_exit.setSizePolicy(sizePolicy)
        self.PB_interrview_exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_interrview_exit.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/power.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_interrview_exit.setIcon(icon)
        self.PB_interrview_exit.setIconSize(QtCore.QSize(50, 50))
        self.PB_interrview_exit.setObjectName("PB_interrview_exit")
        self.gridLayout.addWidget(self.PB_interrview_exit, 2, 3, 1, 1)
        self.PB_preferences = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_preferences.sizePolicy().hasHeightForWidth())
        self.PB_preferences.setSizePolicy(sizePolicy)
        self.PB_preferences.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_preferences.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/news.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_preferences.setIcon(icon1)
        self.PB_preferences.setIconSize(QtCore.QSize(50, 50))
        self.PB_preferences.setObjectName("PB_preferences")
        self.gridLayout.addWidget(self.PB_preferences, 2, 2, 1, 1)
        self.pb_submittedProjects = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_submittedProjects.sizePolicy().hasHeightForWidth())
        self.pb_submittedProjects.setSizePolicy(sizePolicy)
        self.pb_submittedProjects.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_submittedProjects.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pb_submittedProjects.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/maps.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pb_submittedProjects.setIcon(icon2)
        self.pb_submittedProjects.setIconSize(QtCore.QSize(50, 50))
        self.pb_submittedProjects.setObjectName("pb_submittedProjects")
        self.gridLayout.addWidget(self.pb_submittedProjects, 2, 0, 1, 1)
        self.PB_interviews_find = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_interviews_find.sizePolicy().hasHeightForWidth())
        self.PB_interviews_find.setSizePolicy(sizePolicy)
        self.PB_interviews_find.setMinimumSize(QtCore.QSize(0, 0))
        self.PB_interviews_find.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_interviews_find.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/search-user.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_interviews_find.setIcon(icon3)
        self.PB_interviews_find.setIconSize(QtCore.QSize(50, 50))
        self.PB_interviews_find.setObjectName("PB_interviews_find")
        self.gridLayout.addWidget(self.PB_interviews_find, 0, 0, 1, 1)
        self.pb_incomingprojects = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_incomingprojects.sizePolicy().hasHeightForWidth())
        self.pb_incomingprojects.setSizePolicy(sizePolicy)
        self.pb_incomingprojects.setMinimumSize(QtCore.QSize(0, 0))
        self.pb_incomingprojects.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pb_incomingprojects.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/refresh-page.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pb_incomingprojects.setIcon(icon4)
        self.pb_incomingprojects.setIconSize(QtCore.QSize(50, 50))
        self.pb_incomingprojects.setObjectName("pb_incomingprojects")
        self.gridLayout.addWidget(self.pb_incomingprojects, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_mentor_preference)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 2, 3)
        self.verticalLayout_2.addWidget(self.frame_mentor_preference)
        self.tw_interviews = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tw_interviews.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tw_interviews.setAutoFillBackground(False)
        self.tw_interviews.setStyleSheet("QTableWidget {\n"
"    \n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #f9f9f9;\n"
"    alternate-background-color: #e0e0e0;\n"
"    gridline-color: #ccc;\n"
"    border-radius: 10px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"}")
        self.tw_interviews.setAutoScrollMargin(16)
        self.tw_interviews.setObjectName("tw_interviews")
        self.tw_interviews.setColumnCount(3)
        self.tw_interviews.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tw_interviews.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tw_interviews.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tw_interviews.setHorizontalHeaderItem(2, item)
        self.tw_interviews.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_interviews.horizontalHeader().setDefaultSectionSize(200)
        self.tw_interviews.horizontalHeader().setMinimumSectionSize(22)
        self.verticalLayout_2.addWidget(self.tw_interviews)
        interviews.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=interviews)
        self.statusbar.setObjectName("statusbar")
        interviews.setStatusBar(self.statusbar)

        self.retranslateUi(interviews)
        QtCore.QMetaObject.connectSlotsByName(interviews)

    def retranslateUi(self, interviews):
        _translate = QtCore.QCoreApplication.translate
        interviews.setWindowTitle(_translate("interviews", "INTERVIEWS"))
        self.label.setText(_translate("interviews", "INTERVIEWS"))
        self.PB_interrview_exit.setText(_translate("interviews", "Exit"))
        self.PB_preferences.setText(_translate("interviews", "Main Menu"))
        self.pb_submittedProjects.setText(_translate("interviews", "Submitted Projects"))
        self.PB_interviews_find.setText(_translate("interviews", "Find"))
        self.pb_incomingprojects.setText(_translate("interviews", "Incoming Projects"))
        item = self.tw_interviews.horizontalHeaderItem(0)
        item.setText(_translate("interviews", "Name"))
        item = self.tw_interviews.horizontalHeaderItem(1)
        item.setText(_translate("interviews", "Project Delivery Time"))
        item = self.tw_interviews.horizontalHeaderItem(2)
        item.setText(_translate("interviews", "Project Arrival Time"))
