# Form implementation generated from reading ui file 'c:\Users\kahra\OneDrive\Masaüstü\PROGRAM\PYTHON\PROJECT\PYQT6_PROJECTS\TAMAMLANANLAR\PROJE\VIT_Project\login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ud_login(object):
    def setupUi(self, ud_login):
        ud_login.setObjectName("ud_login")
        ud_login.setEnabled(True)
        ud_login.resize(700, 500)
        ud_login.setMinimumSize(QtCore.QSize(700, 500))
        ud_login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        ud_login.setBaseSize(QtCore.QSize(600, 500))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        ud_login.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/logout.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ud_login.setWindowIcon(icon)
        ud_login.setStyleSheet("QWidget {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 rgba(173, 216, 230, 255), \n"
"        stop:1 rgba(255, 255, 255, 255));\n"
"};\n"
"")
        ud_login.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.Netherlands))
        self.verticalLayout = QtWidgets.QVBoxLayout(ud_login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=ud_login)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.frameIcon = QtWidgets.QFrame(parent=ud_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameIcon.sizePolicy().hasHeightForWidth())
        self.frameIcon.setSizePolicy(sizePolicy)
        self.frameIcon.setMinimumSize(QtCore.QSize(600, 500))
        self.frameIcon.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameIcon.setObjectName("frameIcon")
        self.label_icon = QtWidgets.QLabel(parent=self.frameIcon)
        self.label_icon.setGeometry(QtCore.QRect(0, 20, 581, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon.sizePolicy().hasHeightForWidth())
        self.label_icon.setSizePolicy(sizePolicy)
        self.label_icon.setToolTipDuration(2)
        self.label_icon.setStyleSheet("QPushButton {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"QComboBox {\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #ccc;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"};\n"
" padding: 10px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"")
        self.label_icon.setText("")
        self.label_icon.setPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/WeRHere2.png"))
        self.label_icon.setScaledContents(True)
        self.label_icon.setWordWrap(False)
        self.label_icon.setObjectName("label_icon")
        self.frame = QtWidgets.QFrame(parent=self.frameIcon)
        self.frame.setGeometry(QtCore.QRect(0, 200, 581, 281))
        self.frame.setToolTipDuration(2)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.groupbox_user_login = QtWidgets.QGroupBox(parent=self.frame)
        self.groupbox_user_login.setGeometry(QtCore.QRect(25, 0, 541, 191))
        self.groupbox_user_login.setStyleSheet("QComboBox {\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #ccc;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"")
        self.groupbox_user_login.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.groupbox_user_login.setObjectName("groupbox_user_login")
        self.label_user_name = QtWidgets.QLabel(parent=self.groupbox_user_login)
        self.label_user_name.setGeometry(QtCore.QRect(14, 30, 141, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_user_name.setFont(font)
        self.label_user_name.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_user_name.setStyleSheet("QLabel {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QLabel:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: #005f73;\n"
"}")
        self.label_user_name.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_user_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_user_name.setObjectName("label_user_name")
        self.lineedit_user_login = QtWidgets.QLineEdit(parent=self.groupbox_user_login)
        self.lineedit_user_login.setGeometry(QtCore.QRect(180, 35, 351, 59))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.lineedit_user_login.setFont(font)
        self.lineedit_user_login.setToolTipDuration(1)
        self.lineedit_user_login.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}")
        self.lineedit_user_login.setInputMask("")
        self.lineedit_user_login.setText("")
        self.lineedit_user_login.setObjectName("lineedit_user_login")
        self.label_password = QtWidgets.QLabel(parent=self.groupbox_user_login)
        self.label_password.setGeometry(QtCore.QRect(14, 93, 141, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_password.setFont(font)
        self.label_password.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_password.setStyleSheet("QLabel {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QLabel:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: #005f73;\n"
"}")
        self.label_password.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.lineedit_password = QtWidgets.QLineEdit(parent=self.groupbox_user_login)
        self.lineedit_password.setGeometry(QtCore.QRect(180, 100, 351, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.lineedit_password.setFont(font)
        self.lineedit_password.setToolTipDuration(1)
        self.lineedit_password.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}")
        self.lineedit_password.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.lineedit_password.setText("")
        self.lineedit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineedit_password.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineedit_password.setClearButtonEnabled(False)
        self.lineedit_password.setObjectName("lineedit_password")
        self.label_error = QtWidgets.QLabel(parent=self.groupbox_user_login)
        self.label_error.setGeometry(QtCore.QRect(190, 159, 331, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_error.setFont(font)
        self.label_error.setToolTipDuration(-2)
        self.label_error.setStyleSheet("Qlabel{\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(182, 29, 10);\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    margin: 5px;\n"
"}")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.lineedit_user_login.raise_()
        self.label_user_name.raise_()
        self.label_password.raise_()
        self.lineedit_password.raise_()
        self.label_error.raise_()
        self.pushbutton_login = QtWidgets.QPushButton(parent=self.frame)
        self.pushbutton_login.setGeometry(QtCore.QRect(210, 200, 171, 60))
        self.pushbutton_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_login.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/login.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushbutton_login.setIcon(icon1)
        self.pushbutton_login.setIconSize(QtCore.QSize(50, 50))
        self.pushbutton_login.setObjectName("pushbutton_login")
        self.pushbutton_exit = QtWidgets.QPushButton(parent=self.frame)
        self.pushbutton_exit.setGeometry(QtCore.QRect(390, 200, 171, 61))
        self.pushbutton_exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_exit.setStyleSheet("QPushButton {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/power.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushbutton_exit.setIcon(icon2)
        self.pushbutton_exit.setIconSize(QtCore.QSize(50, 50))
        self.pushbutton_exit.setObjectName("pushbutton_exit")
        self.horizontalLayout.addWidget(self.frameIcon)
        self.widget_2 = QtWidgets.QWidget(parent=ud_login)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 13)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ud_login)
        QtCore.QMetaObject.connectSlotsByName(ud_login)

    def retranslateUi(self, ud_login):
        _translate = QtCore.QCoreApplication.translate
        ud_login.setWindowTitle(_translate("ud_login", "User Login Window"))
        self.groupbox_user_login.setTitle(_translate("ud_login", "User Login"))
        self.label_user_name.setText(_translate("ud_login", "User Name : "))
        self.lineedit_user_login.setPlaceholderText(_translate("ud_login", "User Name"))
        self.label_password.setText(_translate("ud_login", "Password: "))
        self.lineedit_password.setPlaceholderText(_translate("ud_login", "Password"))
        self.pushbutton_login.setText(_translate("ud_login", "Login"))
        self.pushbutton_login.setShortcut(_translate("ud_login", "Return"))
        self.pushbutton_exit.setText(_translate("ud_login", "Exit"))
        self.pushbutton_exit.setShortcut(_translate("ud_login", "Ctrl+E"))
