# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mw_main_menu(object):
    def setupUi(self, mw_main_menu):
        mw_main_menu.setObjectName("mw_main_menu")
        mw_main_menu.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        mw_main_menu.setEnabled(True)
        mw_main_menu.resize(600, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mw_main_menu.sizePolicy().hasHeightForWidth())
        mw_main_menu.setSizePolicy(sizePolicy)
        mw_main_menu.setMinimumSize(QtCore.QSize(600, 500))
        mw_main_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        mw_main_menu.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        mw_main_menu.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/manage.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        mw_main_menu.setWindowIcon(icon)
        mw_main_menu.setToolTip("")
        mw_main_menu.setStatusTip("")
        mw_main_menu.setAccessibleDescription("")
        mw_main_menu.setStyleSheet("QWidget {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 rgba(173, 216, 230, 255), \n"
"        stop:1 rgba(255, 255, 255, 255));\n"
"};\n"
"")
        mw_main_menu.setAnimated(False)
        mw_main_menu.setDocumentMode(False)
        mw_main_menu.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=mw_main_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(11, 11, -1, -1)
        self.gridLayout.setHorizontalSpacing(14)
        self.gridLayout.setVerticalSpacing(26)
        self.gridLayout.setObjectName("gridLayout")
        self.pushbutton_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushbutton_logout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_logout.setStyleSheet("QPushButton {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/logout.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushbutton_logout.setIcon(icon1)
        self.pushbutton_logout.setIconSize(QtCore.QSize(40, 40))
        self.pushbutton_logout.setObjectName("pushbutton_logout")
        self.gridLayout.addWidget(self.pushbutton_logout, 3, 0, 1, 1)
        self.frame_icon = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_icon.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_icon.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_icon.setObjectName("frame_icon")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_icon)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_icon)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/WeRHere2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.frame_icon, 0, 0, 1, 2)
        self.pushbutton_applications = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_applications.sizePolicy().hasHeightForWidth())
        self.pushbutton_applications.setSizePolicy(sizePolicy)
        self.pushbutton_applications.setMinimumSize(QtCore.QSize(96, 55))
        self.pushbutton_applications.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_applications.setStyleSheet("QPushButton {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/contacts.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushbutton_applications.setIcon(icon2)
        self.pushbutton_applications.setIconSize(QtCore.QSize(50, 50))
        self.pushbutton_applications.setObjectName("pushbutton_applications")
        self.gridLayout.addWidget(self.pushbutton_applications, 1, 0, 1, 1)
        self.pushbutton_admin_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushbutton_admin_menu.setEnabled(True)
        self.pushbutton_admin_menu.setMinimumSize(QtCore.QSize(0, 70))
        self.pushbutton_admin_menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_admin_menu.setStyleSheet("QPushButton {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}")
        self.pushbutton_admin_menu.setIcon(icon)
        self.pushbutton_admin_menu.setIconSize(QtCore.QSize(50, 50))
        self.pushbutton_admin_menu.setObjectName("pushbutton_admin_menu")
        self.gridLayout.addWidget(self.pushbutton_admin_menu, 2, 1, 1, 1)
        self.pushbutton_mentor_meeting = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushbutton_mentor_meeting.setMinimumSize(QtCore.QSize(0, 70))
        self.pushbutton_mentor_meeting.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_mentor_meeting.setStyleSheet("QPushButton {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/referrals.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushbutton_mentor_meeting.setIcon(icon3)
        self.pushbutton_mentor_meeting.setIconSize(QtCore.QSize(50, 50))
        self.pushbutton_mentor_meeting.setObjectName("pushbutton_mentor_meeting")
        self.gridLayout.addWidget(self.pushbutton_mentor_meeting, 1, 1, 1, 1)
        self.pushbutton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushbutton_exit.setMinimumSize(QtCore.QSize(0, 55))
        self.pushbutton_exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_exit.setStyleSheet("QPushButton {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/power.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushbutton_exit.setIcon(icon4)
        self.pushbutton_exit.setIconSize(QtCore.QSize(50, 50))
        self.pushbutton_exit.setObjectName("pushbutton_exit")
        self.gridLayout.addWidget(self.pushbutton_exit, 3, 1, 1, 1)
        self.pushbutton_interviews = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_interviews.sizePolicy().hasHeightForWidth())
        self.pushbutton_interviews.setSizePolicy(sizePolicy)
        self.pushbutton_interviews.setMinimumSize(QtCore.QSize(0, 55))
        self.pushbutton_interviews.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushbutton_interviews.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushbutton_interviews.setStyleSheet("QPushButton {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/members.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushbutton_interviews.setIcon(icon5)
        self.pushbutton_interviews.setIconSize(QtCore.QSize(50, 50))
        self.pushbutton_interviews.setObjectName("pushbutton_interviews")
        self.gridLayout.addWidget(self.pushbutton_interviews, 2, 0, 1, 1)
        mw_main_menu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=mw_main_menu)
        self.statusbar.setObjectName("statusbar")
        mw_main_menu.setStatusBar(self.statusbar)

        self.retranslateUi(mw_main_menu)
        QtCore.QMetaObject.connectSlotsByName(mw_main_menu)

    def retranslateUi(self, mw_main_menu):
        _translate = QtCore.QCoreApplication.translate
        mw_main_menu.setWindowTitle(_translate("mw_main_menu", "Main Menu"))
        self.pushbutton_logout.setText(_translate("mw_main_menu", "Logout"))
        self.pushbutton_applications.setText(_translate("mw_main_menu", "Applications"))
        self.pushbutton_admin_menu.setText(_translate("mw_main_menu", "Admin Menu"))
        self.pushbutton_mentor_meeting.setText(_translate("mw_main_menu", "Mentor Meeting"))
        self.pushbutton_exit.setText(_translate("mw_main_menu", "Exit"))
        self.pushbutton_interviews.setText(_translate("mw_main_menu", "Interviews"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw_main_menu = QtWidgets.QMainWindow()
    ui = Ui_mw_main_menu()
    ui.setupUi(mw_main_menu)
    mw_main_menu.show()
    sys.exit(app.exec())
