# Form implementation generated from reading ui file 'c:\Users\kahra\OneDrive\Masaüstü\PROGRAM\PYTHON\PROJECT\PYQT6_PROJECTS\TAMAMLANANLAR\PROJE\VIT_Project\Mentor.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mentor(object):
    def setupUi(self, Mentor):
        Mentor.setObjectName("Mentor")
        Mentor.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Mentor.setEnabled(True)
        Mentor.resize(1064, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mentor.sizePolicy().hasHeightForWidth())
        Mentor.setSizePolicy(sizePolicy)
        Mentor.setMinimumSize(QtCore.QSize(0, 0))
        Mentor.setSizeIncrement(QtCore.QSize(0, 0))
        Mentor.setBaseSize(QtCore.QSize(1228, 805))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        Mentor.setFont(font)
        Mentor.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        Mentor.setStyleSheet("QWidget {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"        stop:0 rgba(173, 216, 230, 255), \n"
"        stop:1 rgba(255, 255, 255, 255));\n"
"};\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=Mentor)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 95))
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: #005f73;\n"
"}border-radius: 10px;\n"
"background-color: #008CBA;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame_mentor_preference = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_mentor_preference.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_mentor_preference.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_mentor_preference.setObjectName("frame_mentor_preference")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_mentor_preference)
        self.gridLayout.setObjectName("gridLayout")
        self.PB_mentor_preferences = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_mentor_preferences.sizePolicy().hasHeightForWidth())
        self.PB_mentor_preferences.setSizePolicy(sizePolicy)
        self.PB_mentor_preferences.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_mentor_preferences.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/news.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_mentor_preferences.setIcon(icon)
        self.PB_mentor_preferences.setIconSize(QtCore.QSize(50, 50))
        self.PB_mentor_preferences.setObjectName("PB_mentor_preferences")
        self.gridLayout.addWidget(self.PB_mentor_preferences, 2, 0, 1, 1)
        self.PB_Mentor_Find = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_Mentor_Find.sizePolicy().hasHeightForWidth())
        self.PB_Mentor_Find.setSizePolicy(sizePolicy)
        self.PB_Mentor_Find.setMinimumSize(QtCore.QSize(140, 0))
        self.PB_Mentor_Find.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_Mentor_Find.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/search-user.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_Mentor_Find.setIcon(icon1)
        self.PB_Mentor_Find.setIconSize(QtCore.QSize(50, 50))
        self.PB_Mentor_Find.setObjectName("PB_Mentor_Find")
        self.gridLayout.addWidget(self.PB_Mentor_Find, 0, 1, 1, 1)
        self.PB_mentor_all_interviews = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_mentor_all_interviews.sizePolicy().hasHeightForWidth())
        self.PB_mentor_all_interviews.setSizePolicy(sizePolicy)
        self.PB_mentor_all_interviews.setMinimumSize(QtCore.QSize(225, 0))
        self.PB_mentor_all_interviews.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_mentor_all_interviews.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/profile.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_mentor_all_interviews.setIcon(icon2)
        self.PB_mentor_all_interviews.setIconSize(QtCore.QSize(50, 50))
        self.PB_mentor_all_interviews.setObjectName("PB_mentor_all_interviews")
        self.gridLayout.addWidget(self.PB_mentor_all_interviews, 0, 0, 1, 1)
        self.comboBox_Mentor = QtWidgets.QComboBox(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Mentor.sizePolicy().hasHeightForWidth())
        self.comboBox_Mentor.setSizePolicy(sizePolicy)
        self.comboBox_Mentor.setMinimumSize(QtCore.QSize(0, 59))
        self.comboBox_Mentor.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.comboBox_Mentor.setStyleSheet("QComboBox {\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #ccc;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"")
        self.comboBox_Mentor.setObjectName("comboBox_Mentor")
        self.comboBox_Mentor.addItem("")
        self.comboBox_Mentor.addItem("")
        self.comboBox_Mentor.addItem("")
        self.comboBox_Mentor.addItem("")
        self.comboBox_Mentor.addItem("")
        self.comboBox_Mentor.addItem("")
        self.comboBox_Mentor.addItem("")
        self.comboBox_Mentor.addItem("")
        self.gridLayout.addWidget(self.comboBox_Mentor, 2, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_mentor_preference)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 2, 1)
        self.PB_mentor_exit = QtWidgets.QPushButton(parent=self.frame_mentor_preference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_mentor_exit.sizePolicy().hasHeightForWidth())
        self.PB_mentor_exit.setSizePolicy(sizePolicy)
        self.PB_mentor_exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PB_mentor_exit.setStyleSheet("QPushButton {\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #007B9E;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #005f73;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\kahra\\OneDrive\\Masaüstü\\PROGRAM\\PYTHON\\PROJECT\\PYQT6_PROJECTS\\TAMAMLANANLAR\\PROJE\\VIT_Project\\icons/power.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PB_mentor_exit.setIcon(icon3)
        self.PB_mentor_exit.setIconSize(QtCore.QSize(50, 50))
        self.PB_mentor_exit.setObjectName("PB_mentor_exit")
        self.gridLayout.addWidget(self.PB_mentor_exit, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_mentor_preference)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setSizeIncrement(QtCore.QSize(883, 450))
        self.tableWidget.setBaseSize(QtCore.QSize(883, 450))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    \n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"    background-color: #f9f9f9;\n"
"    alternate-background-color: #e0e0e0;\n"
"    gridline-color: #ccc;\n"
"    border-radius: 10px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #008CBA;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(154)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
        self.tableWidget.verticalHeader().setMinimumSectionSize(38)
        self.verticalLayout_2.addWidget(self.tableWidget)
        Mentor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Mentor)
        self.statusbar.setObjectName("statusbar")
        Mentor.setStatusBar(self.statusbar)

        self.retranslateUi(Mentor)
        QtCore.QMetaObject.connectSlotsByName(Mentor)

    def retranslateUi(self, Mentor):
        _translate = QtCore.QCoreApplication.translate
        Mentor.setWindowTitle(_translate("Mentor", "MENTOR"))
        self.label.setText(_translate("Mentor", "MENTOR"))
        self.PB_mentor_preferences.setText(_translate("Mentor", "Main Menu"))
        self.PB_Mentor_Find.setText(_translate("Mentor", " Find     "))
        self.PB_mentor_all_interviews.setText(_translate("Mentor", "All Interviews"))
        self.comboBox_Mentor.setItemText(0, _translate("Mentor", "It would be appropriate for him to participate in the entire VIT project."))
        self.comboBox_Mentor.setItemText(1, _translate("Mentor", "It would be appropriate for him to receive initial IT training in the VIT project and be directed to ITPH."))
        self.comboBox_Mentor.setItemText(2, _translate("Mentor", "It would be appropriate for him to receive English training in the VIT project and be directed to ITPH."))
        self.comboBox_Mentor.setItemText(3, _translate("Mentor", "It would be appropriate for him to be directed directly to ITPH within the scope of the VIT project."))
        self.comboBox_Mentor.setItemText(4, _translate("Mentor", "It would be appropriate for him to be directed to work with direct individual coaching."))
        self.comboBox_Mentor.setItemText(5, _translate("Mentor", "It would be more appropriate for him to participate in the next VIT project."))
        self.comboBox_Mentor.setItemText(6, _translate("Mentor", "He should be directed to another sector."))
        self.comboBox_Mentor.setItemText(7, _translate("Mentor", "Others."))
        self.PB_mentor_exit.setText(_translate("Mentor", "Exit      "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Mentor", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Mentor", "Surname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Mentor", "Interview Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Mentor", "Mentor"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Mentor", "IT Knowledge"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Mentor", "Intensity"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Mentor", "Comments"))
